name: Reusable Container Scan

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  container-scan:
    name: Trivy Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ inputs.image }}
          severity: CRITICAL
          exit-code: 1
          ignore-unfixed: true
